# This workflow will build a Java project with Gradle
# For more information check: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Hash Generator

on:
  workflow_run:
    workflows:
      - Java CI with Gradle
    types:
      - completed
    
jobs:   
  hash:
   runs-on: windows-2019

   steps:
    
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.workflow_run.head_branch }}
    - name: Hash the artifacts file
      uses: Amadevus/pwsh-script@v2.0.1
      with:
          # PowerShell script to execute in Actions-hydrated context
          script: certutil -hashfile Artifacts.zip sha256 > hash.md
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Hash
        path: ./hash.md
